### ISSUE TITLE
package github.com/casbin/casbin/v2/effect: cannot find package

### ISSUE THREAD

**Issue by alobaidan** [casbin/casbin-authz-plugin#23]
**sorry for distrube you

I run cabin many times
 but i tride to run it today i got this message****

```
 $ go get github.com/casbin/casbin-authz-plugin
package github.com/casbin/casbin/v2/effect: cannot find package "github.com/casbin/casbin/v2/effect" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/effect (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/effect (from $GOPATH)
package github.com/casbin/casbin/v2/log: cannot find package "github.com/casbin/casbin/v2/log" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/log (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/log (from $GOPATH)
package github.com/casbin/casbin/v2/model: cannot find package "github.com/casbin/casbin/v2/model" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/model (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/model (from $GOPATH)
package github.com/casbin/casbin/v2/persist: cannot find package "github.com/casbin/casbin/v2/persist" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/persist (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/persist (from $GOPATH)
package github.com/casbin/casbin/v2/persist/file-adapter: cannot find package "github.com/casbin/casbin/v2/persist/file-adapter" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from $GOPATH)
package github.com/casbin/casbin/v2/rbac: cannot find package "github.com/casbin/casbin/v2/rbac" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/rbac (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/rbac (from $GOPATH)
package github.com/casbin/casbin/v2/rbac/default-role-manager: cannot find package "github.com/casbin/casbin/v2/rbac/default-role-manager" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager (from $GOPATH)
package github.com/casbin/casbin/v2/util: cannot find package "github.com/casbin/casbin/v2/util" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/util (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/util (from $GOPATH)
```

**could you tell me how i van sovle it please ?**

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-authz-plugin/commit/e61c2503c4b942fe4176b535922695c42ee8d567

**Comment by alobaidan** [comment]
Many Thanks and sorry for  distrube you again

**Comment by alobaidan** [comment]
still not fixed , the same error

 go get github.com/casbin/casbin-authz-plugin
package github.com/casbin/casbin/v2/effect: cannot find package "github.com/casb                                                                             in/casbin/v2/effect" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/effect (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/effect (from $GOPATH)
package github.com/casbin/casbin/v2/log: cannot find package "github.com/casbin/                                                                             casbin/v2/log" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/log (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/log (from $GOPATH)
package github.com/casbin/casbin/v2/model: cannot find package "github.com/casbi                                                                             n/casbin/v2/model" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/model (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/model (from $GOPATH)
package github.com/casbin/casbin/v2/persist: cannot find package "github.com/cas                                                                             bin/casbin/v2/persist" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/persist (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/persist (from $GOPATH)
package github.com/casbin/casbin/v2/persist/file-adapter: cannot find package "g                                                                             ithub.com/casbin/casbin/v2/persist/file-adapter" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from                                                                              $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from $                                                                             GOPATH)
package github.com/casbin/casbin/v2/rbac: cannot find package "github.com/casbin                                                                             /casbin/v2/rbac" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/rbac (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/rbac (from $GOPATH)
package github.com/casbin/casbin/v2/rbac/default-role-manager: cannot find packa                                                                             ge "github.com/casbin/casbin/v2/rbac/default-role-manager" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager                                                                              (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager (f                                                                             rom $GOPATH)
package github.com/casbin/casbin/v2/util: cannot find package "github.com/casbin                                                                             /casbin/v2/util" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/util (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/util (from $GOPATH)

**Comment by hsluoyz** [comment]
Fixed

**Comment by alobaidan** [comment]
still not fixed , the same error please see below

go get github.com/casbin/casbin-authz-plugin
package github.com/casbin/casbin/v2/effect: cannot find package "github.com/casb                                                                             in/casbin/v2/effect" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/effect (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/effect (from $GOPATH)
package github.com/casbin/casbin/v2/log: cannot find package "github.com/casbin/                                                                             casbin/v2/log" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/log (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/log (from $GOPATH)
package github.com/casbin/casbin/v2/model: cannot find package "github.com/casbi                                                                             n/casbin/v2/model" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/model (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/model (from $GOPATH)
package github.com/casbin/casbin/v2/persist: cannot find package "github.com/cas                                                                             bin/casbin/v2/persist" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/persist (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/persist (from $GOPATH)
package github.com/casbin/casbin/v2/persist/file-adapter: cannot find package "g                                                                             ithub.com/casbin/casbin/v2/persist/file-adapter" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from                                                                              $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from $                                                                             GOPATH)
package github.com/casbin/casbin/v2/rbac: cannot find package "github.com/casbin                                                                             /casbin/v2/rbac" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/rbac (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/rbac (from $GOPATH)
package github.com/casbin/casbin/v2/rbac/default-role-manager: cannot find packa                                                                             ge "github.com/casbin/casbin/v2/rbac/default-role-manager" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager                                                                              (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager (f                                                                             rom $GOPATH)
package github.com/casbin/casbin/v2/util: cannot find package "github.com/casbin                                                                             /casbin/v2/util" in any of:
        /usr/local/go/src/github.com/casbin/casbin/v2/util (from $GOROOT)
        /home/pi/go/src/github.com/casbin/casbin/v2/util (from $GOPATH)

**Comment by alobaidan** [comment]
![error](https://user-images.githubusercontent.com/14161637/65040980-9ced0900-d94d-11e9-9b5d-c8f157068e18.png)

this is screenshot show the error

**Comment by alobaidan** [comment]
this is screenshot error after upgrade go version to 1.12.
![error 2](https://user-images.githubusercontent.com/14161637/65042151-2a315d00-d950-11e9-9423-c209993b3c32.png)

**Comment by alobaidan** [comment]
this is screenshout error after upgrade go version to 1.12
![error 2](https://user-images.githubusercontent.com/14161637/65042220-4f25d000-d950-11e9-832a-7e1c49f15adb.png)
